---
title: "Explore the First sample"
output: html_notebook
---

Library
```{r}
library(readr)
library(haven)
library(dplyr)
library(purrr)

```

Open file
```{r}
MD <- read_csv("C:/Users/thoma/SHARE/Firstsample/Emb.csv")
MD$X1 = NULL

#View(MD)
```

Observations
```{r}
# Calculate and print the percentage of NA values for each column
na_percentages_MD <- colMeans(is.na(MD)) * 100
print(na_percentages_MD)
hist(na_percentages_MD)

#I explore the variables one by one and write down those that should not be deleted
na_percentages_MD_20 <- na_percentages_MD[na_percentages_MD >= 20]
print(na_percentages_MD_20)
```
dn018_ dn019_ dn027_1

ph002_ ph003_ > à surveiller

TEST
```{r}

##TEST1
#sharew1 <- read_dta("C:/Users/thoma/SHARE/sharew1_rel8-0-0_ALL_datasets_stata/sharew1_rel8-0-0_dn.dta")

##Calculate and print the percentage of NA values for each column
#na_percentages_dn_origin <- colMeans(is.na(sharew1)) * 100
#print(na_percentages_dn_origin)
#mean_dn_origin = mean(na_percentages_dn_origin)

##TEST2
#a = sum(is.na(MD$dn035_))/length(MD$dn035_) * 100
#b = sum(is.na(MD$dn014_))/length(MD$dn014_) * 100




```

Remove rows and columns when the proportion of NA exceeds 20 % 
```{r}

# Threshold for NA values
na_threshold <- 0.2

# List of columns to exclude from removal
exclude_columns <- c("dn018_", "dn019_", "dn027_1", "br003_", "br006_")

# Store names of columns to be removed
removed_columns <- names(MD)[colSums(is.na(MD)) / nrow(MD) >= na_threshold]

# Number of variables to remove
lrm = length(removed_columns)

# Print names of removed columns
#print(removed_columns)


# List of column to remove after all

MDF = MD

# Columns to be set to NULL
columns_to_remove = c("hhid1.x", "mergeidp1.x", "coupleid1.x","country.x","language.x", "br017_","hhid1.y", "mergeidp1.y", "coupleid1.y", "language.y", "country.y", "dn002_", "mergeidp1.x.x", "coupleid1.x.x","hhid1.x.x", "language.x.x", "country.x.x", "mergeidp1.y.y", "coupleid1.y.y", "language.y.y", "country.y.y", "hhid1.y.y", "dn038_","ph055_")

MDF <- MDF %>% select(-all_of(columns_to_remove))


MDF <- MDF %>%
  select(-c(mh002_:mh017_))

MDF <- MDF %>%
  select(-c(euro1:euro12))


# Remove columns with more than "na_threshold" NA, excluding specified columns
MDF <- MDF[, !(colSums(is.na(MDF)) / nrow(MDF) >= na_threshold & !names(MDF) %in% exclude_columns)]
```

We remove row with NAs > 20%
```{r}
# Remove rows with more than "na_threshold" NA
MDF <- MDF[rowSums(is.na(MDF)) / ncol(MDF) < na_threshold, ]
```

Now we calculate EuroD (Euro-D) score to reduce data
```{r}
# Transform -1 and -2 by NA

column_index_mh002_ <- which(names(MDF) == "mh002_")
column_index_mh0017_ <- which(names(MDF) == "mh017_")


for (i in column_index_mh002_:column_index_mh0017_) {
  MDF[, i][MDF[, i] == -1] <- NA
  MDF[, i][MDF[, i] == -2] <- NA
}

# Testing result
vectest = unlist(MDF[column_index_mh002_:column_index_mh0017_])
unique_values <- unique(vectest)
unique_values

#Some items seem inversed

MDF$test = NA

for (i in MDF$mh003_) {
  if (!is.na(MDF$mh003_[i])) {
    if (MDF$test[i] == 1) {
      MDF$mh003_[i] <- 0
    } else if (MDF$mh003_[i] == 0) {
      MDF$mh003_[i] <- 1
    }
  }
}
```


